### ISSUE TITLE
Error building elephant-bird-pig

### ISSUE THREAD

**Issue by phui** [twitter/elephant-bird#450]
**Update #2** I checked the online repo mentioned in the error

    Failure to find com.twitter.elephantbird:elephant-bird-core:jar:tests:4.11-SNAPSHOT in http://maven.twttr.com

http://maven.twttr.com/com/twitter/elephant-bird/

It is empty. What should I do?

---

**Update #1** It is not duplicate of force update question.

I tried

    mvn clean install -U -Dprotobuf.version=2.5.0 -Dmaven.test.skip=true -Dmaven.repo.local=localrepo

which produced the same error, except that it starts downloading files again and it takes longer to get to the error.

---
**Original Content**

I have been working hard (**12 hours+**) trying to install elephant-bird locally in my <code>$HOME</code> in a shared research-purpose cluster. after **12 hours+** of hard work, I am still lost in the ocean. Any kind man who cares to pull me up to a boat?

I have strived to install the correct versions of <code>protocol-buffers</code> (version 2.5.0) and <code>thrift</code> (version 0.7.0).

Executing version check gives:

    $ protoc --version
    libprotoc 2.5.0
    $ thrift -version
    Thrift version 0.7.0

Ok, all looks fine. download elephant-bird by

    git clone git://github.com/kevinweil/elephant-bird.git

CD into the directory and run

    mvn -Dprotobuf.version=2.5.0 -Dmaven.test.skip=true package

<code>-Dprotobuf.version=2.5.0</code> is advised by the [official github][1] of elephant-bird for I am running a non-default version of <code>protocol-buffers</code>. <code>-Dmaven.test.skip=true</code> is advised by [this post][2] because I did fail some tests during elephant-bird-core build.

    [INFO] ------------------------------------------------------------------------
    [INFO] Building Elephant Bird Pig 4.11-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO] 
    [INFO] Elephant Bird ...................................... SUCCESS [  0.643 s]
    [INFO] Elephant Bird Hadoop Compatibility ................. SUCCESS [  2.514 s]
    [INFO] Elephant Bird Core ................................. SUCCESS [ 25.494 s]
    [INFO] Elephant Bird Cascading2 ........................... SUCCESS [  2.650 s]
    [INFO] Elephant Bird Crunch ............................... SUCCESS [  3.218 s]
    [INFO] Elephant Bird Hive ................................. SUCCESS [  2.342 s]
    [INFO] Elephant Bird Pig .................................. FAILURE [  0.238 s]
    [INFO] Elephant Bird Mahout ............................... SKIPPED
    [INFO] Elephant Bird RCFile ............................... SKIPPED
    [INFO] Elephant Bird Lucene ............................... SKIPPED
    [INFO] Elephant Bird Pig Lucene ........................... SKIPPED
    [INFO] Elephant Bird Examples ............................. SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 37.748 s
    [INFO] Finished at: 2015-10-10T20:02:11-04:00
    [INFO] Final Memory: 48M/964M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal on project elephant-bird-pig: Could not resolve dependencies for project com.twitter.elephantbird:elephant-bird-pig:jar:4.11-SNAPSHOT: Failure to find com.twitter.elephantbird:elephant-bird-core:jar:tests:4.11-SNAPSHOT in http://maven.twttr.com was cached in the local repository, resolution will not be reattempted until the update interval of twitter has elapsed or updates are forced -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
    [ERROR] 
    [ERROR] After correcting the problems, you can resume the build with the command
    [ERROR]   mvn <goals> -rf :elephant-bird-pig

Well, let's run the same command with <code>-X</code>:

    [INFO]                                                                         
    [INFO] ------------------------------------------------------------------------
    [INFO] Building Elephant Bird Pig 4.11-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
    [DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
    [DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
    ....
    Skipping >>>>>>>
    ....
    [DEBUG]       commons-codec:commons-codec:jar:1.4:compile
    [DEBUG]       commons-net:commons-net:jar:1.4.1:provided
    [DEBUG]       org.mortbay.jetty:jetty:jar:6.1.26:provided
    [DEBUG]          org.mortbay.jetty:servlet-api:jar:2.5-20081211:provided
    [DEBUG]       org.mortbay.jetty:jetty-util:jar:6.1.26:provided
    [DEBUG]       tomcat:jasper-runtime:jar:5.5.12:provided
    [DEBUG]       tomcat:jasper-compiler:jar:5.5.12:provided
    [DEBUG]       org.mortbay.jetty:jsp-api-2.1:jar:6.1.14:provided
    [DEBUG]       org.mortbay.jetty:jsp-2.1:jar:6.1.14:provided
    [DEBUG]          org.eclipse.jdt:core:jar:3.1.1:provided
    [DEBUG]          ant:ant:jar:1.6.5:test (scope managed from compile by com.twitter.elephantbird:elephant-bird:4.11-SNAPSHOT)
    [DEBUG]       commons-el:commons-el:jar:1.0:provided
    [DEBUG]       net.java.dev.jets3t:jets3t:jar:0.7.1:provided
    [DEBUG]       org.mortbay.jetty:servlet-api-2.5:jar:6.1.14:provided
    [DEBUG]       net.sf.kosmosfs:kfs:jar:0.3:provided
    [DEBUG]       junit:junit:jar:4.8.2:test (scope managed from compile by com.twitter.elephantbird:elephant-bird:4.11-SNAPSHOT) (version managed from 4.8.1 by com.twitter.elephantbird:elephant-bird:4.11-SNAPSHOT)
    [DEBUG]       hsqldb:hsqldb:jar:1.8.0.10:provided
    [DEBUG]       oro:oro:jar:2.0.8:provided
    [DEBUG]       org.apache.avro:avro:jar:1.5.3:provided
    [DEBUG]          com.thoughtworks.paranamer:paranamer:jar:2.3:provided
    [DEBUG]          org.xerial.snappy:snappy-java:jar:1.0.3.2:provided
    [DEBUG]    org.antlr:antlr:jar:3.4:provided
    [DEBUG]       org.antlr:antlr-runtime:jar:3.4:provided
    [DEBUG]          org.antlr:stringtemplate:jar:3.2.1:provided
    [DEBUG]          antlr:antlr:jar:2.7.7:provided
    [DEBUG]       org.antlr:ST4:jar:4.0.4:provided
    [DEBUG]    joda-time:joda-time:jar:1.6:provided
    [DEBUG]    org.codehaus.jackson:jackson-mapper-asl:jar:1.8.8:provided
    [DEBUG]       org.codehaus.jackson:jackson-core-asl:jar:1.8.8:provided
    [DEBUG]    log4j:log4j:jar:1.2.17:test
    [DEBUG]    org.easymock:easymock:jar:3.1:test
    [DEBUG]       cglib:cglib-nodep:jar:2.2.2:test
    [DEBUG]       org.objenesis:objenesis:jar:1.2:test
    [DEBUG] Could not find metadata com.twitter.elephantbird:elephant-bird-core:4.11-SNAPSHOT/maven-metadata.xml in local (/home/huip/.m2/repository)
    [DEBUG] Failure to find com.twitter.elephantbird:elephant-bird-core:4.11-SNAPSHOT/maven-metadata.xml in http://maven.twttr.com was cached in the local repository, resolution will not be reattempted until the update interval of twitter has elapsed or updates are forced
    [DEBUG] Failure to find com.twitter.elephantbird:elephant-bird-core:4.11-SNAPSHOT/maven-metadata.xml in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO] 
    [INFO] Elephant Bird ...................................... SUCCESS [  0.661 s]
    [INFO] Elephant Bird Hadoop Compatibility ................. SUCCESS [  1.462 s]
    [INFO] Elephant Bird Core ................................. SUCCESS [ 13.790 s]
    [INFO] Elephant Bird Cascading2 ........................... SUCCESS [  0.397 s]
    [INFO] Elephant Bird Crunch ............................... SUCCESS [  0.533 s]
    [INFO] Elephant Bird Hive ................................. SUCCESS [  0.567 s]
    [INFO] Elephant Bird Pig .................................. FAILURE [  0.215 s]
    [INFO] Elephant Bird Mahout ............................... SKIPPED
    [INFO] Elephant Bird RCFile ............................... SKIPPED
    [INFO] Elephant Bird Lucene ............................... SKIPPED
    [INFO] Elephant Bird Pig Lucene ........................... SKIPPED
    [INFO] Elephant Bird Examples ............................. SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 18.260 s
    [INFO] Finished at: 2015-10-10T20:17:39-04:00
    [INFO] Final Memory: 23M/964M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal on project elephant-bird-pig: Could not resolve dependencies for project com.twitter.elephantbird:elephant-bird-pig:jar:4.11-SNAPSHOT: Failure to find com.twitter.elephantbird:elephant-bird-core:jar:tests:4.11-SNAPSHOT in http://maven.twttr.com was cached in the local repository, resolution will not be reattempted until the update interval of twitter has elapsed or updates are forced -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project elephant-bird-pig: Could not resolve dependencies for project com.twitter.elephantbird:elephant-bird-pig:jar:4.11-SNAPSHOT: Failure to find com.twitter.elephantbird:elephant-bird-core:jar:tests:4.11-SNAPSHOT in http://maven.twttr.com was cached in the local repository, resolution will not be reattempted until the update interval of twitter has elapsed or updates are forced
    	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:220)
    	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
    	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
    	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
    	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
    	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:606)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.twitter.elephantbird:elephant-bird-pig:jar:4.11-SNAPSHOT: Failure to find com.twitter.elephantbird:elephant-bird-core:jar:tests:4.11-SNAPSHOT in http://maven.twttr.com was cached in the local repository, resolution will not be reattempted until the update interval of twitter has elapsed or updates are forced
    	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:198)
    	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
    	... 22 more
    Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find com.twitter.elephantbird:elephant-bird-core:jar:tests:4.11-SNAPSHOT in http://maven.twttr.com was cached in the local repository, resolution will not be reattempted until the update interval of twitter has elapsed or updates are forced
    	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
    	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:192)
    	... 23 more
    Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find com.twitter.elephantbird:elephant-bird-core:jar:tests:4.11-SNAPSHOT in http://maven.twttr.com was cached in the local repository, resolution will not be reattempted until the update interval of twitter has elapsed or updates are forced
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:459)
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:262)
    	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
    	... 24 more
    Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.twitter.elephantbird:elephant-bird-core:jar:tests:4.11-SNAPSHOT in http://maven.twttr.com was cached in the local repository, resolution will not be reattempted until the update interval of twitter has elapsed or updates are forced
    	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:232)
    	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:599)
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:518)
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:436)
    	... 26 more
    [ERROR] 
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
    [ERROR] 
    [ERROR] After correcting the problems, you can resume the build with the command
    [ERROR]   mvn <goals> -rf :elephant-bird-pig

What now?

  [1]: https://github.com/twitter/elephant-bird#version-compatibility
  [2]: http://stackoverflow.com/questions/20181345/elephant-bird-mvn-package-error

**Comment by ianoc** [comment]
You shouldn't be using github.com/kevinweil/elephant-bird.git, should be github.com/twitter/elephant-bird.git

But did you try do mvn install rather than mvn package as your goal? The odds are to build later things the projects require the previous ones installed. Strange maven quirk that this doesn't seem to be implied often

**Comment by phui** [comment]
Yes, in update1 I tried:

    mvn clean install -U -Dprotobuf.version=2.5.0 -Dmaven.test.skip=true -Dmaven.repo.local=localrepo

I will try with github.com/twitter/elephant-bird.git and report back

**Comment by phui** [comment]
Here is the nohup.out for rerunning the command

    mvn clean install -U -Dprotobuf.version=2.5.0 -Dmaven.test.skip=true -Dmaven.repo.local=localrepo

with github.com/kevinweil/elephant-bird.git. It is the same output, same error:

http://m.uploadedit.com/ba3k/1444597355624.txt

**Comment by ianoc** [comment]
I suspect you want there -DskipTests=true rather the maven.test.skip since its skipping compiling the tests

**Comment by phui** [comment]
Victory declared! Thank you very much for the help.

Do you know a good list of these general flags in Maven so that I can learn something and not be stupid next time?

**Comment by ianoc** [comment]
just google for maven documentation, its just what i did to give you your answer...

**Comment by phui** [comment]
For future reference:

http://stackoverflow.com/questions/24727536/maven-skip-tests
