### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by heapxor** [twitter/elephant-bird#474]
Hi,
Im desperately trying to install the git version of elephant-bird; latest thrift+protobuf were installed accordingly. 

I executed mvn package and got error below

[ERROR] Failed to execute goal com.github.igor-petruk.protobuf:protobuf-maven-plugin:0.6.5:run (default) on project elephant-bird-core: 'protoc' failed. Exit code 0 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.igor-petruk.protobuf:protobuf-maven-plugin:0.6.5:run (default) on project elephant-bird-core: 'protoc' failed. Exit code 0
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: 'protoc' failed. Exit code 0
        at com.github.igor_petruk.protobuf.maven.plugin.RunMojo.printErrorAndThrow(RunMojo.java:430)
        at com.github.igor_petruk.protobuf.maven.plugin.RunMojo.printErrorAndThrow(RunMojo.java:434)
        at com.github.igor_petruk.protobuf.maven.plugin.RunMojo.detectProtobufVersion(RunMojo.java:405)
        at com.github.igor_petruk.protobuf.maven.plugin.RunMojo.execute(RunMojo.java:230)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]

Thanks

**Comment by nishantkumar1292** [comment]
@heapxor Is your issue solved? I am getting the same error.

**Comment by jiawang1** [comment]
hey:
I get the same error. and solved by following way:
1 check my protobuf version by protoc --version (  it is 2.5.0 )
2 find mvn pom file, the version for protobuf, and I change the dependency version to 2.5.0.
then rebuild.
Hope this can help some one

**Comment by rjoberon** [comment]
You can also supply the version to Maven with the command line option `-Dprotobuf.version=2.5.0`.
